version: '3.8'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    ports:
      - "8081:8080"
    environment:
      - KC_DB=mysql
      - KC_DB_URL=jdbc:mysql://bj-cdb-mr8p7rc2.sql.tencentcdb.com:25808/keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=JFhVZbJeYOagCxLKP4IajN7QPKrzwcki,
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
    command: start-dev
